name: Build and deploy runner
on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
    name: Build runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Enable corepack
        run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: yarn run build
        run: yarn run build
      - name: Upload artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    needs: build
    name: Deploy runner
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
